
package com.onlinebuyer.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPserverInterface", targetNamespace = "http://service.onlineshop.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SOAPserverInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.onlineshop.com/SOAPserverInterface/additemtocartRequest", output = "http://service.onlineshop.com/SOAPserverInterface/additemtocartResponse")
    public String additemtocart(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.onlineshop.com/SOAPserverInterface/removefromcartRequest", output = "http://service.onlineshop.com/SOAPserverInterface/removefromcartResponse")
    public String removefromcart(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.onlineshop.com/SOAPserverInterface/smartphonelistRequest", output = "http://service.onlineshop.com/SOAPserverInterface/smartphonelistResponse")
    public String smartphonelist();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.onlineshop.com/SOAPserverInterface/viewcartRequest", output = "http://service.onlineshop.com/SOAPserverInterface/viewcartResponse")
    public String viewcart(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.onlineshop.com/SOAPserverInterface/buyitemsRequest", output = "http://service.onlineshop.com/SOAPserverInterface/buyitemsResponse")
    public String buyitems(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.onlineshop.com/SOAPserverInterface/hometheaterlistRequest", output = "http://service.onlineshop.com/SOAPserverInterface/hometheaterlistResponse")
    public String hometheaterlist();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.onlineshop.com/SOAPserverInterface/laptoplistRequest", output = "http://service.onlineshop.com/SOAPserverInterface/laptoplistResponse")
    public String laptoplist();

}
